name: CI Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            docker:
                image: docker:24.0.5
                options: --privileged
                ports:
                    - 8000:8000
        
        steps:
            - name: check code
              uses: actions/checkout@v3


            - name: python steup
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"


            - name: Dependencies install
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Build docker image
              run: |
                docker build -t oneclick-cloud 
            
            - name: Docker image built successfully 
              run: echo "Docker image built"

            - name: run tests
              run: |
                pytest
            - name: CI Success
              run: echo "All steps completed successfully!"